---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - slurm.ay.dev
  resources:
  - slurmdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - slurm.ay.dev
  resources:
  - slurmdeployments/finalizers
  verbs:
  - update
- apiGroups:
  - slurm.ay.dev
  resources:
  - slurmdeployments/status
  verbs:
  - get
  - patch
  - update
