apiVersion: v1
entries:
  common:
  - annotations:
      category: Infrastructure
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 2.22.0
    created: "2025-02-20T13:58:39.316734056+08:00"
    description: A Library Helm Chart for grouping common logic between bitnami charts.
      This chart is not deployable by itself.
    digest: f08ada920444add76d87a23c588089bfa1a59dd9cf516abe47bbc8aa0da9aee4
    home: https://bitnami.com
    icon: https://bitnami.com/downloads/logos/bitnami-mark.png
    keywords:
    - common
    - helper
    - template
    - function
    - bitnami
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: common
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/common
    type: library
    urls:
    - charts/common-2.22.0.tgz
    version: 2.22.0
  mariadb:
  - annotations:
      category: Database
      images: |
        - name: mariadb
          image: docker.io/bitnami/mariadb:11.4.3-debian-12-r0
        - name: mysqld-exporter
          image: docker.io/bitnami/mysqld-exporter:0.15.1-debian-12-r30
        - name: os-shell
          image: docker.io/bitnami/os-shell:12-debian-12-r27
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 11.4.3
    created: "2025-02-20T13:58:39.320463712+08:00"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: MariaDB is an open source, community-developed SQL database server
      that is widely in use around the world due to its enterprise features, flexibility,
      and collaboration with leading tech firms.
    digest: ed780b0bcd454aabbbbaed5974e735b918757e649112175bd63c9ee015217a90
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/mariadb/img/mariadb-stack-220x234.png
    keywords:
    - mariadb
    - mysql
    - database
    - sql
    - prometheus
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: mariadb
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/mariadb
    urls:
    - charts/mariadb-19.0.6.tgz
    version: 19.0.6
generated: "2025-02-20T13:58:39.30157758+08:00"
