apiVersion: slurm.ay.dev/v1
kind: SlurmDeployment
metadata:
  labels:
    app.kubernetes.io/name: slurm-operator
    app.kubernetes.io/managed-by: kustomize
  name: lensing
spec:
  chart:
    name: slurm
    repository: https://aaronyang0628.github.io/helm-chart-mirror/charts/slurm
    version: 1.0.10
    namespace: slurm-nadc
  job:
    command: ["sh", "-c"]
    args: ["srun -N 2 /bin/hostname"]
  values:
    mariadb:
      enabled: true
      port: 3306
      primary:
        persistence:
          enabled: true
          storageClass: "nas-nm129-25ge-si000958a3ec"
          size: 8Gi
    auth:
      ssh:
        configmap:
          name: slurm-ssh-auth-keys
          prefabPubKeys: ["ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDrL/S9z3HpNMiJ369nnoLzaZlDdNQYtdrd29I5OV/HJkiYKxvz52WN8juwiwI50gIbTeRjxpmSmVFZErWfCx4ysb8dAt9j9PhD2hZuer56f3hnhABmwvyfZWEgj7Vyg4M8kNIMfmomrHjmwPCw4M6U03Afi/ux+O0kOd+qhZB2HTLJIjhmbDXrSblshA/sfoa2L9dofQkhzyrpu+/YpaVMfzyTBBCA8YN9EskbCp1Mk2iiXLUwGJBws2XGMK9bUuuomia4fQS5+wkuJ+Nov1zc2mLRH4b+Ze43q1vlKWZMTS8x5vIrUyM5S8EHzNZ8BYrskBCTpJfwDidjfclvJODYVngFeaEcOIBg+tbbTmEcuPH6MsiLUIsHXIMOpi+ZrX8CUMYYlqLS24wHJkG+FU2vFMEMeqyqIsZOs7AqtpnUQHOEiFSiUpacoB+ZM17TSjk4XSgjtYDZtHItJ65I64w4Tr88Y2OhsXmrYOdaVqVzdTEDrSHlbZ4+YdE15dwKRyk= 21430@Blwsye"]
    persistence:
      shared:
        enabled: true
        accessModes:
          - ReadWriteMany
        name: slurm-shared-storage
        storageClass: "nas-nm129-25ge-si000958a3ec"
        size: 8Gi
    munged:
      image:
        registry: docker-registry.lab.zverse.space
        repository: data-and-computing/slurm-munged
        tag: "25.05"
    slurmdbd:
      image:
        registry: docker-registry.lab.zverse.space
        repository: data-and-computing/slurm-slurmdbd
        tag: "25.05"
    slurmctld:
      image:
        registry: docker-registry.lab.zverse.space
        repository: data-and-computing/slurm-slurmctld
        tag: "25.05"
    login:
      image:
        registry: docker-registry.lab.zverse.space
        repository: data-and-computing/slurm-login
        tag: 25.05-open-mpi
    slurmdCPU:
      replicaCount: 1
      image:
        registry: docker-registry.lab.zverse.space
        repository: data-and-computing/slurm-slurmd
        tag: 25.05-open-mpi
      resources: 
        requests:
          socket: 2
          core-per-socket: 1
          thread-per-core: 1
          ephemeral-storage: 10Gi
          memory: 4Gi
      nodeSelector: {}
    slurmdGPU:
      replicaCount: 1
      nodeAffinityPreset:
        key: "kubernetes.io/hostname"
        values: ["node5"]
        weight: 0
      image:
        registry: docker-registry.lab.zverse.space
        repository: data-and-computing/slurm-slurmd
        tag: 25.05-open-mpi
      resources: 
        requests:
          socket: 2
          core-per-socket: 1
          thread-per-core: 1
          ephemeral-storage: 10Gi
          memory: 4Gi