apiVersion: slurm.ay.dev/v1
kind: SlurmDeployment
metadata:
  labels:
    app.kubernetes.io/name: slurm-operator
    app.kubernetes.io/managed-by: kustomize
  name: lensing
spec:
  chart:
    name: slurm
    repository: https://aaronyang0628.github.io/helm-chart-mirror/charts/slurm
    version: 1.0.9
    namespace: test
  job:
    command: ["sh", "-c"]
    args: ["srun -N 2 /bin/hostname"]
  values:
    mariadb:
      enabled: true
      port: 3306
      primary:
        persistence:
          enabled: false
    auth:
      ssh:
        configmap:
          name: slurm-ssh-auth-keys
          prefabPubKeys: ["ssh-rsa sample_public_key"]
    persistence:
      shared:
        enabled: true
        accessModes:
          - ReadWriteMany
        name: slurm-shared-storage
        storageClass: ""
        size: 8Gi
    munged:
      image:
        registry: docker-registry.lab.zverse.space
        repository: data-and-computing/slurm-munged
        tag: "25.05"
    slurmdbd:
      image:
        registry: docker-registry.lab.zverse.space
        repository: data-and-computing/slurm-slurmdbd
        tag: "25.05"
    slurmctld:
      image:
        registry: docker-registry.lab.zverse.space
        repository: data-and-computing/slurm-slurmctld
        tag: "25.05"
    login:
      image:
        registry: docker-registry.lab.zverse.space
        repository: data-and-computing/slurm-login
        tag: 25.05-open-mpi
    slurmdCPU:
      replicaCount: 1
      image:
        registry: docker-registry.lab.zverse.space
        repository: data-and-computing/slurm-slurmd
        tag: 25.05-open-mpi
      resources: 
        requests:
          core: 1
          cpu: 500m
          ephemeral-storage: 10Gi
          memory: 1Gi
  